stateDiagram-v2
    direction LR
    [*] --> Normal

    Normal --> Panico : Botón tocado
    Panico --> Normal : Botón sostenido 3s

    Normal --> Bradicardia : Frecuencia baja
    Bradicardia --> Normal : Frecuencia normal

    Normal --> Taquicardia : Frecuencia alta
    Taquicardia --> Normal : Frecuencia normal

    Panico --> Enviando : Registrado en red
    Bradicardia --> Enviando : Registrado en red
    Taquicardia --> Enviando : Registrado en red

    Enviando --> Normal : Mensaje enviado

