flowchart TD

    A[Inicio del ciclo] --> B[Leer botón]
    B --> C[Medir frecuencia cardíaca]
    C --> D[Obtener ubicación]

    D --> E{¿Botón tocado?}
    E -->|Sí| F[Generar alerta de pánico]
    E -->|No| G{¿Frecuencia baja?}

    G -->|Sí| H[Generar alerta de bradicardia]
    G -->|No| I{¿Frecuencia alta?}

    I -->|Sí| J[Generar alerta de taquicardia]
    I -->|No| K[Continuar sin alerta]

    F --> L
    H --> L
    J --> L
    K --> L

    L[Consultar intensidad de señal] --> M{¿Señal válida?}

    M -->|No| N[Mostrar mensaje: sin señal]
    M -->|Sí| O[Consultar registro en red]

    O --> P{¿Registrado en red y Hay Alerta?}
    P -->|No| Q[Mostrar mensaje: sin registro]
    P -->|Sí| R[Enviar mensaje con datos]

    R --> S[Fin del ciclo]
    Q --> S
    N --> S
